/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uii.customer;

import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.Car;
import model.CarHistory;

/**
 *
 * @author niyat
 */
public class customercreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form customercreateJPanel
     */
  
      CarHistory history;
     
     public customercreateJPanel( CarHistory history) {
        initComponents();
        this.history=history;
        
        populateTable();
       
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblyear = new javax.swing.JLabel();
        lblmanufacturer = new javax.swing.JLabel();
        lblavail = new javax.swing.JLabel();
        lbllocation = new javax.swing.JLabel();
        txtavailability = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtserialno = new javax.swing.JTextField();
        txtexpirydate = new javax.swing.JTextField();
        lblname = new javax.swing.JLabel();
        txtcarmanufacturer = new javax.swing.JTextField();
        txtseats = new javax.swing.JTextField();
        txtmodelno = new javax.swing.JTextField();
        lblexpiry = new javax.swing.JLabel();
        lblseats = new javax.swing.JLabel();
        lblmodelno = new javax.swing.JLabel();
        txtmanufactureryear = new javax.swing.JTextField();
        txtcolorr = new javax.swing.JTextField();
        lblserialno = new javax.swing.JLabel();
        txtlocation = new javax.swing.JTextField();
        lblcolor = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtfiltername = new javax.swing.JTextField();
        BTNVIEW = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 255));

        jTable1.setBackground(new java.awt.Color(204, 204, 255));
        jTable1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Serial Number", "MANUFACTURER", "MANUFACTURING YEAR", "MODEL NUMBER", "NO OF SEATS", "EXPIRY DATE", "AVAILABILITY", "LOCTION", "COLOR"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        lblyear.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblyear.setText("CAR MANUFACTURING YEAR :");

        lblmanufacturer.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblmanufacturer.setText("CAR MANUFACTURER :");

        lblavail.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblavail.setText("CAR AVAILABILITY :");

        lbllocation.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lbllocation.setText("CAR LOCATION :");

        txtavailability.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N

        txtName.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N

        txtserialno.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N

        txtexpirydate.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N

        lblname.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblname.setText("CAR NAME :");

        txtcarmanufacturer.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N

        txtseats.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N

        txtmodelno.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        txtmodelno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmodelnoActionPerformed(evt);
            }
        });

        lblexpiry.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblexpiry.setText("MAINTENANCE CERTIFICATE EXPIRY DATE :");

        lblseats.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblseats.setText("NUMBER OF SEATS :");

        lblmodelno.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblmodelno.setText("CAR MODEL NUMBER :");

        txtmanufactureryear.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        txtmanufactureryear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmanufactureryearActionPerformed(evt);
            }
        });

        txtcolorr.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N

        lblserialno.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblserialno.setText("CAR SERIAL NUMBER :");

        txtlocation.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N

        lblcolor.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblcolor.setText("CAR COLOR :");

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setBackground(new java.awt.Color(204, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("         SEARCH :");

        txtfiltername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfilternameActionPerformed(evt);
            }
        });
        txtfiltername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtfilternameKeyReleased(evt);
            }
        });

        BTNVIEW.setBackground(new java.awt.Color(204, 204, 255));
        BTNVIEW.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BTNVIEW.setText("VIEW DETAILS");
        BTNVIEW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNVIEWActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(317, 317, 317)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(txtfiltername, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(BTNVIEW, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BTNVIEW, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfiltername, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblname, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblserialno, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblyear, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblmanufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtcarmanufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtserialno, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtmanufactureryear, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblmodelno, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtmodelno, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblexpiry, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtexpirydate, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblseats, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtseats, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblavail, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtavailability, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblcolor, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtcolorr, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbllocation, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtlocation, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblname, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblseats, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtseats, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblserialno, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtserialno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblexpiry, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtexpirydate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblmanufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtcarmanufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblavail, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtavailability, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtmanufactureryear, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblyear, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblcolor, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtcolorr, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblmodelno, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtmodelno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtlocation, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbllocation, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtfilternameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfilternameActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtfilternameActionPerformed

    private void txtfilternameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfilternameKeyReleased
        // TODO add your handling code here:
        String query=txtfiltername.getText().toLowerCase();
        filter(query);

    }//GEN-LAST:event_txtfilternameKeyReleased

    private void BTNVIEWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNVIEWActionPerformed
        // TODO add your handling code here:
        
        int selectedRowIndex = jTable1.getSelectedRow();
        
        if(selectedRowIndex<0){
            JOptionPane.showMessageDialog(this, "Insert data doesn't match.");
            return;
        }
         DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
         Car selectedcars = (Car)model.getValueAt(selectedRowIndex, 0);
         
         txtName.setText(selectedcars.getCar_name());
         txtserialno.setText(String.valueOf(selectedcars.getSerialnumber()));
         txtmanufactureryear.setText(String.valueOf(selectedcars.getManufactureryear()));
         txtcarmanufacturer.setText(selectedcars.getCar_manufacturer());
         txtmodelno.setText(String.valueOf(selectedcars.getModel_no()));
         txtseats.setText(selectedcars.getNo_seats());
         txtlocation.setText(selectedcars.getCar_location());
         txtavailability.setText((selectedcars.getAvailability()));
         txtexpirydate.setText(String.valueOf(selectedcars.getMaintenancecertificate_date()));
         txtcolorr.setText(selectedcars.getColor()); 
         
         
    }//GEN-LAST:event_BTNVIEWActionPerformed

    private void txtmodelnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmodelnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmodelnoActionPerformed

    private void txtmanufactureryearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmanufactureryearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmanufactureryearActionPerformed

    
    
    
    
     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNVIEW;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblavail;
    private javax.swing.JLabel lblcolor;
    private javax.swing.JLabel lblexpiry;
    private javax.swing.JLabel lbllocation;
    private javax.swing.JLabel lblmanufacturer;
    private javax.swing.JLabel lblmodelno;
    private javax.swing.JLabel lblname;
    private javax.swing.JLabel lblseats;
    private javax.swing.JLabel lblserialno;
    private javax.swing.JLabel lblyear;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtavailability;
    private javax.swing.JTextField txtcarmanufacturer;
    private javax.swing.JTextField txtcolorr;
    private javax.swing.JTextField txtexpirydate;
    private javax.swing.JTextField txtfiltername;
    private javax.swing.JTextField txtlocation;
    private javax.swing.JTextField txtmanufactureryear;
    private javax.swing.JTextField txtmodelno;
    private javax.swing.JTextField txtseats;
    private javax.swing.JTextField txtserialno;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        
        
                 
                 
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
         model.setRowCount(0);
         
         for(Car vs : history.getHistory()){
             
             Object[] row = new Object[10];
             row[0]= vs;
              row[1] = vs.getSerialnumber();
             row[2]= vs.getCar_manufacturer();  
              row[3] = vs.getManufactureryear();
              row[4] = vs.getModel_no();
              row[5]= vs.getNo_seats();
              row[6] = vs.getMaintenancecertificate_date();
              row[7] = vs.getAvailability();
              row[8] = vs.getCar_location();
              row[9] = vs.getColor();
             
             
              model.addRow(row);
              
                 
             
    }
}
    
      private void filter(String query)
         {
             

              DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
              TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
              jTable1.setRowSorter(tr);
              tr.setRowFilter(RowFilter.regexFilter(query));
         }
}
