/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uiiadmin;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Car;
import model.CarHistory;

/**
 *
 * @author niyat
 */
public class adminviewJpanel extends javax.swing.JPanel {

    /**
     * Creates new form adminviewJpanel
     */
    
    CarHistory history;
    public adminviewJpanel(CarHistory history) {
        initComponents();
        this.history=history;
       
        
        
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblexpiry = new javax.swing.JLabel();
        lblseats = new javax.swing.JLabel();
        lblmodelno = new javax.swing.JLabel();
        txtmanufactureryear = new javax.swing.JTextField();
        txtcolorr = new javax.swing.JTextField();
        txtlocation = new javax.swing.JTextField();
        lblyear = new javax.swing.JLabel();
        lblavail = new javax.swing.JLabel();
        txtavailability = new javax.swing.JTextField();
        txtserialno = new javax.swing.JTextField();
        txtexpirydate = new javax.swing.JTextField();
        lblname = new javax.swing.JLabel();
        txtcarmanufacturer = new javax.swing.JTextField();
        txtseats = new javax.swing.JTextField();
        txtmodelno = new javax.swing.JTextField();
        lblserialno = new javax.swing.JLabel();
        lblcolor = new javax.swing.JLabel();
        lblmanufacturer = new javax.swing.JLabel();
        lbllocation = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblcars = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        BTNVIEW = new javax.swing.JButton();
        BTNDELETE = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnyes = new javax.swing.JRadioButton();
        btnno = new javax.swing.JRadioButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1015, Short.MAX_VALUE)
        );

        jSplitPane1.setLeftComponent(jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 204, 255));

        lblexpiry.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblexpiry.setText("MAINTENANCE CERTIFICATE EXPIRY DATE :");

        lblseats.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblseats.setText("NUMBER OF SEATS :");

        lblmodelno.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblmodelno.setText("CAR MODEL NUMBER :");

        txtmanufactureryear.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        txtmanufactureryear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmanufactureryearActionPerformed(evt);
            }
        });

        txtcolorr.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N

        txtlocation.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N

        lblyear.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblyear.setText("CAR MANUFACTURING YEAR :");

        lblavail.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblavail.setText("CAR AVAILABILITY :");

        txtavailability.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N

        txtserialno.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N

        txtexpirydate.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N

        lblname.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblname.setText("CAR NAME :");

        txtcarmanufacturer.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N

        txtseats.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N

        txtmodelno.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        txtmodelno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmodelnoActionPerformed(evt);
            }
        });

        lblserialno.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblserialno.setText("CAR SERIAL NUMBER :");

        lblcolor.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblcolor.setText("CAR COLOR :");

        lblmanufacturer.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblmanufacturer.setText("CAR MANUFACTURER :");

        lbllocation.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lbllocation.setText("CAR LOCATION :");

        txtName.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N

        tblcars.setBackground(new java.awt.Color(204, 204, 255));
        tblcars.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblcars.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tblcars.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NAME", "SERIAL NUMBER", "MANUFACTURER NAME", "MANUFACTURING YEAR", "MODEL NUMBER", "NUMBER OF SEATS", "MAINTENENCE EXPIRY DATE", "AVAILABILITY", "LOCATION", "COLOR"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblcars);

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        BTNVIEW.setBackground(new java.awt.Color(204, 204, 255));
        BTNVIEW.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        BTNVIEW.setText(" VIEW  ");
        BTNVIEW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNVIEWActionPerformed(evt);
            }
        });

        BTNDELETE.setBackground(new java.awt.Color(204, 204, 255));
        BTNDELETE.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        BTNDELETE.setText("DELETE");
        BTNDELETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNDELETEActionPerformed(evt);
            }
        });

        btnupdate.setBackground(new java.awt.Color(204, 204, 255));
        btnupdate.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnupdate.setText("UPDATE");
        btnupdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnupdateMouseClicked(evt);
            }
        });
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        jButton1.setText("GET CSV");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(BTNVIEW, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTNDELETE, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNVIEW, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNDELETE, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setBackground(new java.awt.Color(204, 204, 255));
        jLabel1.setFont(new java.awt.Font("Palatino Linotype", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("                            UBER RENTALS DATA");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(344, 344, 344)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(532, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel1.getAccessibleContext().setAccessibleName("            UBER RENTALS");

        buttonGroup1.add(btnyes);
        btnyes.setText("yes");

        buttonGroup1.add(btnno);
        btnno.setText("No");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblname, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblserialno, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblyear, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblmanufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtcarmanufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtserialno, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtmanufactureryear, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblmodelno, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtmodelno, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnyes)
                                .addGap(18, 18, 18)
                                .addComponent(btnno)))))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblexpiry, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtexpirydate, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblseats, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtseats, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblavail, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtavailability, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblcolor, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtcolorr, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbllocation, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtlocation, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane2)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblname, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblseats, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtseats, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblserialno, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtserialno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblexpiry, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtexpirydate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblmanufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtcarmanufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblavail, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtavailability, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtmanufactureryear, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblyear, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblcolor, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtcolorr, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblmodelno, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtmodelno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtlocation, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbllocation, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnyes)
                    .addComponent(btnno))
                .addContainerGap(144, Short.MAX_VALUE))
        );

        jSplitPane1.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BTNDELETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNDELETEActionPerformed
        // TODO add your handling code here:
        
        int selectedRowIndex = tblcars.getSelectedRow();
        
        if(selectedRowIndex<0){
            JOptionPane.showMessageDialog(this, "Please select a Row to Delete");
            return;
        }
         DefaultTableModel model = (DefaultTableModel) tblcars.getModel();
         Car selectedcars = (Car)model.getValueAt(selectedRowIndex, 0);
         
         history.deletecars(selectedcars);
         
         JOptionPane.showMessageDialog(this, "Car details deleted.");
         
                txtName.setText("");
                 txtavailability.setText("");
                 txtcarmanufacturer.setText("");
                 txtexpirydate.setText("");
                 txtlocation.setText("");
                 txtmanufactureryear.setText("");
                 txtmodelno.setText("");
                 txtserialno.setText("");
                 txtseats.setText("");
                 txtcolorr.setText("");
                 
         
         
         populateTable();
    }//GEN-LAST:event_BTNDELETEActionPerformed

    
    
    
    
    private void BTNVIEWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNVIEWActionPerformed
        // TODO add your handling code here:
        
         int selectedRowIndex = tblcars.getSelectedRow();
        
        if(selectedRowIndex<0){
            JOptionPane.showMessageDialog(this, "Please select a Row to View");
            return;
        }
        
        
           
          
     
         DefaultTableModel model = (DefaultTableModel) tblcars.getModel();
         Car selectedcars = (Car)model.getValueAt(selectedRowIndex, 0);
         
         txtName.setText(selectedcars.getCar_name());
         txtserialno.setText(String.valueOf(selectedcars.getSerialnumber()));
         txtmanufactureryear.setText((selectedcars.getManufactureryear()));
         txtcarmanufacturer.setText(selectedcars.getCar_manufacturer());
         txtmodelno.setText(String.valueOf(selectedcars.getModel_no()));
         txtlocation.setText(selectedcars.getCar_location());
         txtavailability.setText((selectedcars.getAvailability()));
         txtexpirydate.setText(String.valueOf(selectedcars.getMaintenancecertificate_date()));
         txtcolorr.setText(selectedcars.getColor()); 
         txtseats.setText(selectedcars.getNo_seats());
         
        
                 
         
        
    }//GEN-LAST:event_BTNVIEWActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
        
        
        
        
        
        int selectedRowIndex = tblcars.getSelectedRow();
        
        if(selectedRowIndex<0){
            JOptionPane.showMessageDialog(this, "Please select a Row to Update");
            return;
            
        }
        
       
        DefaultTableModel model = (DefaultTableModel) tblcars.getModel();
        
         model.setValueAt(txtName.getText(), selectedRowIndex, 0);
           model.setValueAt(txtserialno.getText(), selectedRowIndex, 1);
            model.setValueAt(txtcarmanufacturer.getText(), selectedRowIndex, 2);
             model.setValueAt(txtmanufactureryear.getText(), selectedRowIndex, 3);
              model.setValueAt(txtmodelno.getText(), selectedRowIndex, 4);
              model.setValueAt(txtseats.getText(), selectedRowIndex, 5);
                model.setValueAt(txtexpirydate.getText(), selectedRowIndex, 6);
                 model.setValueAt(txtavailability.getText(), selectedRowIndex, 7);
                  model.setValueAt(txtlocation.getText(), selectedRowIndex, 8);
                   model.setValueAt(txtcolorr.getText(), selectedRowIndex, 9);
                   
                 
         
         
         
        
        
    }//GEN-LAST:event_btnupdateActionPerformed
    
        
    
    private void btnupdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnupdateMouseClicked
        // TODO add your handling code here:
        
       
        
        
    }//GEN-LAST:event_btnupdateMouseClicked

    private void txtmanufactureryearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmanufactureryearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmanufactureryearActionPerformed

    private void txtmodelnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmodelnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmodelnoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        
         String filePath = "C:\\Users\\niyat\\Documents\\uber2.txt";
        File file = new File(filePath); 
             BufferedReader br;
        try {
            br = new BufferedReader(new FileReader(file));
              DefaultTableModel model = (DefaultTableModel)tblcars.getModel();
          Object[] tableLine = br.lines().toArray();
        for (int i = 0 ; i < tableLine.length; i++){
            Object[] values = tableLine[i].toString().split("/");
          Car ub = history.addnewcars();

     
        
       ub.setCar_name(String.valueOf(values[0]));
       ub.setSerialnumber(Integer.valueOf(values[1].toString()));
        ub.setCar_manufacturer(String.valueOf(values[2]));
       ub.setManufactureryear(String.valueOf(values[3]));
       ub.setModel_no(Integer.valueOf(values[4].toString()));
       ub.setNo_seats(String.valueOf(values[5]) );
       ub.setMaintenancecertificate_date(Integer.valueOf(values[6].toString()));
       ub.setAvailability((String.valueOf(values[7])));
       ub.setCar_location((String.valueOf(values[8])));
       ub.setColor((String.valueOf(values[9])));
       
       

         model.addRow(values);
        }
        }
         catch (FileNotFoundException ex) {
            Logger.getLogger(adminviewJpanel.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        
   
     
    }//GEN-LAST:event_jButton1ActionPerformed

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNDELETE;
    private javax.swing.JButton BTNVIEW;
    private javax.swing.JRadioButton btnno;
    private javax.swing.JButton btnupdate;
    private javax.swing.JRadioButton btnyes;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lblavail;
    private javax.swing.JLabel lblcolor;
    private javax.swing.JLabel lblexpiry;
    private javax.swing.JLabel lbllocation;
    private javax.swing.JLabel lblmanufacturer;
    private javax.swing.JLabel lblmodelno;
    private javax.swing.JLabel lblname;
    private javax.swing.JLabel lblseats;
    private javax.swing.JLabel lblserialno;
    private javax.swing.JLabel lblyear;
    private javax.swing.JTable tblcars;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtavailability;
    private javax.swing.JTextField txtcarmanufacturer;
    private javax.swing.JTextField txtcolorr;
    private javax.swing.JTextField txtexpirydate;
    private javax.swing.JTextField txtlocation;
    private javax.swing.JTextField txtmanufactureryear;
    private javax.swing.JTextField txtmodelno;
    private javax.swing.JTextField txtseats;
    private javax.swing.JTextField txtserialno;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        
        DefaultTableModel model = (DefaultTableModel) tblcars.getModel();
         model.setRowCount(0);
         
         for(Car vs : history.getHistory()){
             
             Object[] row = new Object[10];
             row[0]= vs;
             row[1] = vs.getSerialnumber();
             row[2]= vs.getCar_manufacturer();  
              row[3] = vs.getManufactureryear();
              row[4] = vs.getModel_no();
              row[5]= vs.getNo_seats();
              row[6] = vs.getMaintenancecertificate_date();
              row[7] = vs.getAvailability();
              row[8] = vs.getCar_location();
              row[9] = vs.getColor();
             
             model.addRow(row);
             
                   
        }
         
        
    }
   
}
     
